Repository YAPP-admin/yappu-world-server, pull requests merged in 2025-02, with the labels that each got.

#27 fix: 직군 순서 변경
  .github/workflows/yappu-world-dev-cd.yaml
  src/main/kotlin/co/yappuworld/user/domain/vo/Position.kt
Labels: 수정/리팩토링

#28 feat: 회원 탈퇴
  src/main/kotlin/co/yappuworld/user/application/UserAuthService.kt
  src/main/kotlin/co/yappuworld/user/domain/UserAuthValidator.kt
  src/main/kotlin/co/yappuworld/user/domain/model/User.kt
  src/main/kotlin/co/yappuworld/user/domain/vo/UserError.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthController.kt
  src/test/kotlin/co/yappuworld/support/fixture/user/UserFixture.kt
  src/test/kotlin/co/yappuworld/user/application/UserAuthServiceTest.kt
Labels: 기능

#29 feat: FCM 설정
  .gitignore
  build.gradle.kts
  src/main/kotlin/co/yappuworld/global/client/fcm/FcmClient.kt
  src/main/kotlin/co/yappuworld/global/client/fcm/FcmClientImpl.kt
  src/main/kotlin/co/yappuworld/global/client/fcm/FcmClientInTest.kt
  src/main/kotlin/co/yappuworld/global/config/AppConfig.kt
  src/main/kotlin/co/yappuworld/global/config/FcmConfig.kt
  src/main/kotlin/co/yappuworld/global/property/FcmProperty.kt
  src/main/kotlin/co/yappuworld/user/application/UserAuthAdminService.kt
  src/main/kotlin/co/yappuworld/user/application/UserAuthService.kt
  src/main/kotlin/co/yappuworld/user/application/dto/request/UserSignUpAppRequestDto.kt
  src/main/kotlin/co/yappuworld/user/domain/model/SignUpApplicantDetails.kt
  src/main/kotlin/co/yappuworld/user/domain/model/SignUpApplication.kt
  src/main/kotlin/co/yappuworld/user/domain/model/UserDevice.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/UserDeviceRepository.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/UserSignUpApiRequestDto.kt
  src/main/resources/application-fcm.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/test/kotlin/co/yappuworld/support/fixture/user/UserFixture.kt
  src/test/kotlin/co/yappuworld/user/application/UserAuthServiceTest.kt
  src/test/kotlin/co/yappuworld/user/application/UserAuthSignUpApplicationServiceTest.kt
  src/test/kotlin/co/yappuworld/user/application/UserLoginServiceTest.kt
  src/test/kotlin/co/yappuworld/user/infrastructure/SignUpApplicantDetailsRepositoryConverterTest.kt
Labels: 기능

#30 feat: 유저 알람 설정
  .github/workflows/yappu-world-dev-cd.yaml
  .github/workflows/yappu-world-prod-cd.yaml
  src/main/kotlin/co/yappuworld/global/persistence/CustomConverter.kt
  src/main/kotlin/co/yappuworld/global/response/SuccessResponse.kt
  src/main/kotlin/co/yappuworld/user/application/SignUpService.kt
  src/main/kotlin/co/yappuworld/user/application/UserAlarmService.kt
  src/main/kotlin/co/yappuworld/user/application/UserAuthAdminService.kt
  src/main/kotlin/co/yappuworld/user/application/UserAuthService.kt
  src/main/kotlin/co/yappuworld/user/application/dto/request/UpdateDeviceAlarmAppRequestDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/request/UserSignUpAppRequestDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/MasterAlarmToggleAppResponse.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/UserAlarmStatusAppResponse.kt
  src/main/kotlin/co/yappuworld/user/domain/model/ApplicationDetails.kt
  src/main/kotlin/co/yappuworld/user/domain/model/SignUpApplication.kt
  src/main/kotlin/co/yappuworld/user/domain/model/UserAlarmSetting.kt
  src/main/kotlin/co/yappuworld/user/domain/vo/UserError.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/UserAlarmSettingRepository.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAlarmApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAlarmController.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthAdminController.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthController.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/UpdateDeviceAlarmApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/UserSignUpApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/MasterAlarmToggleApiResponse.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/UserAlarmStatusApiResponse.kt
  src/main/resources/application-dev.yaml
  src/main/resources/application-fcm.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-secret-local.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/test/kotlin/co/yappuworld/support/fixture/user/UserFixture.kt
  src/test/kotlin/co/yappuworld/user/application/AuthServiceTest.kt
  src/test/kotlin/co/yappuworld/user/application/SignUpServiceTest.kt
  src/test/kotlin/co/yappuworld/user/application/UserAuthServiceTest.kt
  src/test/kotlin/co/yappuworld/user/infrastructure/ApplicationDetailsRepositoryConverterTest.kt
Labels: 기능, 수정/리팩토링

#31 feature: 디스코드 알림 설정
  .editorconfig
  .github/workflows/yappu-world-dev-ci.yaml
  .gitignore
  docker/docker-compose-test.yaml
  src/main/kotlin/co/yappuworld/external/discord/DiscordClient.kt
  src/main/kotlin/co/yappuworld/external/discord/DiscordProperty.kt
  src/main/kotlin/co/yappuworld/external/discord/dto/DiscordEmbed.kt
  src/main/kotlin/co/yappuworld/external/discord/dto/DiscordMessage.kt
  src/main/kotlin/co/yappuworld/external/fcm/FcmClient.kt
  src/main/kotlin/co/yappuworld/external/fcm/FcmProperty.kt
  src/main/kotlin/co/yappuworld/global/client/fcm/FcmClient.kt
  src/main/kotlin/co/yappuworld/global/client/fcm/FcmClientInTest.kt
  src/main/kotlin/co/yappuworld/global/config/AppConfig.kt
  src/main/kotlin/co/yappuworld/global/config/FcmConfig.kt
  src/main/kotlin/co/yappuworld/global/security/JwtGenerator.kt
  src/main/kotlin/co/yappuworld/global/security/JwtProperty.kt
  src/main/kotlin/co/yappuworld/global/security/JwtResolver.kt
  src/main/kotlin/co/yappuworld/global/util/TimeUtils.kt
  src/main/kotlin/co/yappuworld/user/application/SignUpService.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/DiscordUserSystemNotifier.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/UserSystemNotifier.kt
  src/main/resources/application-secret-local.yaml
  src/main/resources/application-test.yaml
  src/test/kotlin/co/yappuworld/external/discord/DiscordClientTest.kt
  src/test/kotlin/co/yappuworld/support/fixture/property/PropertyFixture.kt
  src/test/kotlin/co/yappuworld/user/application/SignUpServiceTest.kt
  src/test/kotlin/co/yappuworld/user/application/UserAuthServiceTest.kt
  src/test/kotlin/co/yappuworld/user/infrastructure/ApplicationDetailsRepositoryConverterTest.kt
Labels: 기능

#32 fix: 프로필 조회 API 수정
  src/main/kotlin/co/yappuworld/user/application/dto/response/UserProfileAppResponseDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserProfileApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/UserProfileApiResponseDto.kt
Labels: 수정/리팩토링

#33 feat: FCM TOKEN 수정
  src/main/kotlin/co/yappuworld/global/config/SecurityConfig.kt
  src/main/kotlin/co/yappuworld/global/security/SecurityPathMatchersManager.kt
  src/main/kotlin/co/yappuworld/user/application/UserAlarmService.kt
  src/main/kotlin/co/yappuworld/user/domain/model/UserDevice.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/UserDeviceRepository.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserSystemApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserSystemController.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/UpdateFcmTokenApiRequestDto.kt
  src/main/resources/schema.sql
  src/test/kotlin/co/yappuworld/user/infrastructure/ApplicationDetailsRepositoryConverterTest.kt
Labels: 기능

#34 Sentry 설정
  .github/workflows/yappu-world-dev-cd.yaml
  .github/workflows/yappu-world-dev-ci.yaml
  .github/workflows/yappu-world-prod-cd.yaml
  .github/workflows/yappu-world-prod-ci.yaml
  build.gradle.kts
  settings.gradle.kts
  src/main/kotlin/co/yappuworld/YappuWorldServerApplication.kt
  src/main/kotlin/co/yappuworld/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/co/yappuworld/global/security/JwtResolver.kt
  src/main/kotlin/co/yappuworld/global/security/SecurityPathMatchersManager.kt
  src/main/kotlin/co/yappuworld/global/security/SecurityUser.kt
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
Labels: 인프라

#35 [YPW-68] 공지사항 API 명세 정의
  src/main/kotlin/co/yappuworld/board/presentation/BoardApi.kt
  src/main/kotlin/co/yappuworld/board/presentation/BoardController.kt
Labels: 기능

#37 fix: 토큰 검증 해결을 위한 타임존 설정
  src/main/kotlin/co/yappuworld/global/config/AppInitializer.kt
  src/main/kotlin/co/yappuworld/global/util/TimeUtils.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthController.kt
Labels: 수정/리팩토링

#36 feat: 운영 데이터 설정
  src/main/kotlin/co/yappuworld/operation/domain/Config.kt
  src/main/kotlin/co/yappuworld/operation/presentation/OperationApi.kt
  src/main/kotlin/co/yappuworld/operation/presentation/OperationController.kt
  src/main/kotlin/co/yappuworld/operation/presentation/OperationDataApi.kt
  src/main/kotlin/co/yappuworld/operation/presentation/OperationDataController.kt
  src/main/kotlin/co/yappuworld/operation/presentation/dto/response/ActiveGenerationApiResponseDto.kt
  src/main/kotlin/co/yappuworld/operation/presentation/dto/response/ForceUpdateApiResponseDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserProfileApi.kt
  src/main/resources/data.sql
Labels: 기능

#38 docs: 공통 에러 스웨거 노출
  src/main/kotlin/co/yappuworld/global/config/SwaggerCommonResponse.kt
  src/main/kotlin/co/yappuworld/global/config/SwaggerCommonResponses.kt
  src/main/kotlin/co/yappuworld/global/config/SwaggerConfig.kt
Labels: 문서

#39 fix: 회원가입 이메일 중복 검사
  src/main/kotlin/co/yappuworld/user/application/SignUpService.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthApi.kt
Labels: 수정/리팩토링

#40 feat: 운영진 권한 및 직군 추가
  src/main/kotlin/co/yappuworld/global/config/SecurityConfig.kt
  src/main/kotlin/co/yappuworld/global/security/SecurityPathMatchersManager.kt
  src/main/kotlin/co/yappuworld/user/application/SignUpService.kt
  src/main/kotlin/co/yappuworld/user/domain/vo/Position.kt
  src/main/kotlin/co/yappuworld/user/domain/vo/UserRole.kt
  src/main/resources/data.sql
Labels: 수정/리팩토링

#41 chore: 프로메테우스, 그라파나 세팅
  build.gradle.kts
  docker/docker-compose-dev.yaml
  docker/docker-compose-local.yaml
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/prometheus-local.yaml
Labels: 인프라

#43 feat: 세션 생성
  src/main/kotlin/co/yappuworld/global/security/SecurityPathMatchersManager.kt
  src/main/kotlin/co/yappuworld/schedule/application/ScheduleAdminService.kt
  src/main/kotlin/co/yappuworld/schedule/application/dto/request/ScheduleCreateAppRequestDto.kt
  src/main/kotlin/co/yappuworld/schedule/domain/Schedule.kt
  src/main/kotlin/co/yappuworld/schedule/domain/ScheduleError.kt
  src/main/kotlin/co/yappuworld/schedule/domain/ScheduleType.kt
  src/main/kotlin/co/yappuworld/schedule/domain/Session.kt
  src/main/kotlin/co/yappuworld/schedule/infrastructure/ScheduleRepository.kt
  src/main/kotlin/co/yappuworld/schedule/infrastructure/SessionRepository.kt
  src/main/kotlin/co/yappuworld/schedule/presentation/ScheduleAdminApi.kt
  src/main/kotlin/co/yappuworld/schedule/presentation/ScheduleAdminController.kt
  src/main/kotlin/co/yappuworld/schedule/presentation/dto/request/ScheduleCreateApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/LoginApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/UserProfileApiResponseDto.kt
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/kotlin/co/yappuworld/schedule/infrastructure/ScheduleRepositoryTest.kt
  src/test/kotlin/co/yappuworld/support/fixture/schedule/ScheduleFixture.kt
Labels: 기능

#45 feat: 회원 어드민 API
  build.gradle.kts
  src/main/kotlin/co/yappuworld/global/config/SwaggerConfig.kt
  src/main/kotlin/co/yappuworld/global/response/PageResponse.kt
  src/main/kotlin/co/yappuworld/global/response/SuccessResponse.kt
  src/main/kotlin/co/yappuworld/global/security/SecurityPathMatchersManager.kt
  src/main/kotlin/co/yappuworld/operation/presentation/OperationController.kt
  src/main/kotlin/co/yappuworld/user/application/SignUpService.kt
  src/main/kotlin/co/yappuworld/user/application/UserAdminService.kt
  src/main/kotlin/co/yappuworld/user/application/dto/request/AdminUserPageAppRequestDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/request/UserRoleUpdateAppRequestDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/request/UserSignUpAppRequestDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/ActivityUnitAppResponseDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/UserDetailsAppResponseDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/UserOverviewAppResponseDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/UserOverviewBundleAppResponseDto.kt
  src/main/kotlin/co/yappuworld/user/application/dto/response/UserProfileAppResponseDto.kt
  src/main/kotlin/co/yappuworld/user/domain/model/User.kt
  src/main/kotlin/co/yappuworld/user/domain/model/UserProfile.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/UserRepository.kt
  src/main/kotlin/co/yappuworld/user/infrastructure/model/UserWithLastActivityUnit.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAdminApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAdminController.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAlarmController.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthAdminApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthAdminController.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthApi.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserAuthController.kt
  src/main/kotlin/co/yappuworld/user/presentation/UserProfileController.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/AdminUserPageApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/UserRoleUpdateApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/request/UserSignUpApiRequestDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/ActivityUnitApiResponseDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/AdminUserDetailsApiResponseDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/AdminUserOverviewApiResponseDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/UserProfileApiResponseDto.kt
  src/main/kotlin/co/yappuworld/user/presentation/dto/response/UserRoleApiResponseDto.kt
  src/main/resources/application-local.yaml
  src/test/kotlin/co/yappuworld/support/fixture/user/UserFixture.kt
  src/test/kotlin/co/yappuworld/user/infrastructure/UserRepositoryTest.kt
Labels: 기능
